CREATE DATABASE CHALLENGEDB
GO

USE CHALLENGEDB
GO

CREATE TABLE T_ARCHIVO_MEDICO (
    ID_ARCHIVO_MEDICO SERIAL PRIMARY KEY,
    AUDIOMETRIA VARCHAR(2),
    CAMBIO_PUESTO VARCHAR(2),
    DATOS_MADRE VARCHAR(2000),
    DIAGNOSTICO VARCHAR(100),
    DATOS_OTRO_FAMILIAR VARCHAR(2000),
    DATOS_PADRE VARCHAR(2000),
    EJECTUAR_MICROS VARCHAR(2),
    EJECUTAR_EXTRA VARCHAR(2),
    EVALUACION_VOZ VARCHAR(2),
    FEC_BAJA DATE,
    FEC_ING DATE,
    FEC_MOD DATE,
    FECHA_FIN DATE,
    FECHA_INICIO DATE,
    ID_ESTADO INTEGER,
    ID_TIPO_ARCHIVO_MEDICO INTEGER,
    INCAPACIDAD VARCHAR(2),
    JUNTA_MEDICA VARCHAR(200),
    MOTIVO_BAJA VARCHAR(2000),
    OBSERVACIONES VARCHAR(2000),
    PORCENTAJE_INCAP NUMERIC(10),
    USER_BAJA VARCHAR(2000),
    USER_ING VARCHAR(2000),
    USER_MOD VARCHAR(2000),
    CAMBIO_AREA VARCHAR(2)
);

CREATE TABLE ESTADO (
    ID_ESTADO SERIAL PRIMARY KEY,
    NOMBRE VARCHAR(100),
    DESCRIPCION VARCHAR(500)
);

CREATE TABLE TIPO_ARCHIVO_MEDICO (
    ID_TIPO_ARCHIVO_MEDICO SERIAL PRIMARY KEY,
    NOMBRE VARCHAR(100),
    DESCRIPCION VARCHAR(500)
);

ALTER TABLE T_ARCHIVO_MEDICO
ADD CONSTRAINT FK_ID_ESTADO_ARCHIVO
FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO(ID_ESTADO);

ALTER TABLE T_ARCHIVO_MEDICO
ADD CONSTRAINT FK_ID_TIPO_ARCHIVO
FOREIGN KEY (ID_TIPO_ARCHIVO_MEDICO) REFERENCES TIPO_ARCHIVO_MEDICO(ID_TIPO_ARCHIVO_MEDICO);

INSERT INTO ESTADO (NOMBRE, DESCRIPCION) VALUES 
('Activo', 'Archivo médico activo'),
('Inactivo', 'Archivo médico inactivo');

INSERT INTO TIPO_ARCHIVO_MEDICO (NOMBRE, DESCRIPCION) VALUES 
('Regular', 'Archivo médico regular'),
('Especial', 'Archivo médico especial');