name: .NET 8 Compile

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET 8
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
    
    - name: Show current directory
      run: pwd
      
    - name: List all directories and files (including hidden)
      run: ls -la
      
    - name: List all directories recursively
      run: find . -type d
      
    - name: Find solution file
      run: find . -name "*.sln"
      
    - name: Restore dependencies
      run: |
        solution_file=$(find . -name "*.sln" -type f)
        if [ -z "$solution_file" ]; then
          echo "No solution file found"
          exit 1
        else
          echo "Found solution file at: $solution_file"
          dotnet restore "$solution_file"
        fi
      
    - name: Build
      run: |
        solution_file=$(find . -name "*.sln" -type f)
        dotnet build "$solution_file" --no-restore
